print("Installing tank.lua")
shell.run("wget", "https://raw.githubusercontent.com/Meow-git-hub/tank-game/refs/heads/main/tank.lua", "tank.lua")
print("Installing remote.lua")
shell.run("wget", "https://raw.githubusercontent.com/Meow-git-hub/tank-game/refs/heads/main/remote.lua", "remote.lua")
print("Installing allLevels.txt")
shell.run("wget", "https://raw.githubusercontent.com/Meow-git-hub/tank-game/refs/heads/main/allLevels.txt", "allLevels.txt")
print("Done!")
os.run("exit")
