print("Installing tank.lua")
os.run("wget https://raw.githubusercontent.com/Meow-git-hub/tank-game/refs/heads/main/tank.lua tank.lua")
print("Installing remote.lua")
os.run("wget https://raw.githubusercontent.com/Meow-git-hub/tank-game/refs/heads/main/remote.lua remote.lua")
print("Installing allLevels.txt")
os.run("wget https://raw.githubusercontent.com/Meow-git-hub/tank-game/refs/heads/main/allLevels.txt allLevels.txt")
print("Done!")
os.sleep(2)
os.run("exit")